# Form implementation generated from reading ui file 'aneh.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


# importing libraries
# from PyQt5.QtWidgets import *
# from PyQt5 import QtCore, QtGui
# from PyQt5.QtGui import *
# from PyQt5.QtCore import *
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import *
from PyQt6.QtGui import *
from PyQt6.QtWidgets import *
from client.custom_widgets import ClickableLabel
import qrcode
import sys
from client.QR_data import QR_data
import requests
import json
# from dita_window import ditaWindow

BG_COLOR = '#FFFFFF'
DARK_MODE_BG = '#383a59'
PRIMARY_BLACK = '#000000'
PRIMARY_WHITE = '#FFFFFF'
PRIMARY_BUTTON = '#5561FF'
PRIMARY_GREEN = '#04FFA5'
SECONDARY_GREEN = '#70FFCC'
PURPLE = '#28293D'
BTN_COLOR = 'qlineargradient(x1:0, y1:0, x2:1, y2: 1, stop:0 #5561ff, stop:1 #3643fc);'
BTN_COLOR_HOVER = 'qlineargradient(x1:0, y1:0, x2:1, y2: 1, stop:0 #6b75ff, stop:1 #535fff)'

# # Kalo program udah jadi, buka aja comment ini
# response = requests.get("http://localhost:5000/api/menus/")
# text = response.json()
# makanan = [x for x in text if x['kategori'] == 'makanan']
# minuman = [x for x in text if x['kategori'] == 'minuman']

# Buat ngetes, biar ga request-request dulu
makanan = [{'fotoUrl': 'https://w7.pngwing.com/pngs/201/77/png-transparent-hamburger-veggie-burger-take-out-fast-food-kebab-delicious-beef-burger-burger-with-lettuce-tomato-and-cheese-food-beef-recipe.png', 'harga': 25000, 'id': 1, 'jumlahStok': 0, 'kategori': 'makanan', 'nama': 'Original Burger'}, {'fotoUrl': None, 'harga': 22000, 'id': 2, 'jumlahStok': 0, 'kategori': 'makanan', 'nama': 'Chicken Burger'}, {'fotoUrl': None, 'harga': 40000, 'id': 3, 'jumlahStok': 0, 'kategori': 'makanan', 'nama': 'Beef Burger'}, {'fotoUrl': None, 'harga': 20000, 'id': 4, 'jumlahStok': 0, 'kategori': 'makanan', 'nama': 'Cheese Burger'}]

minuman = [{'fotoUrl': None, 'harga': 8000, 'id': 8, 'jumlahStok': 2, 'kategori': 'minuman', 'nama': 'Coca Cola'}, {'fotoUrl': None, 'harga': 8000, 'id': 7, 'jumlahStok': 2, 'kategori': 'minuman', 'nama': 'Fanta'}, {'fotoUrl': None, 'harga': 8000, 'id': 6, 'jumlahStok': 0, 'kategori': 'minuman', 'nama': 'Sprite'}, {'fotoUrl': None, 'harga': 5000, 'id': 5, 'jumlahStok': 0, 'kategori': 'minuman', 'nama': 'Air Mineral'}]

from PyQt6.QtGui import QFont 

inter10 = QFont()
inter10.setFamily("Inter")
inter10.setPixelSize(10)

inter12 = QFont()
inter12.setFamily("Inter")
inter12.setPixelSize(12)

inter13 = QFont()
inter13.setFamily("Inter")
inter13.setPixelSize(13)

inter14 = QFont()
inter14.setFamily("Inter")
inter14.setPixelSize(14)

inter14bold = QFont()
inter14bold.setFamily("Inter")
inter14bold.setPixelSize(14)
inter14bold.setBold(True)

inter16 = QFont()
inter16.setFamily("Inter")
inter16.setPixelSize(16)

inter24 = QFont()
inter24.setFamily("Inter")
inter24.setPixelSize(24)

inter11 = QFont()
inter11.setFamily("Inter")
inter11.setPixelSize(11)

inter15bold = QFont()
inter15bold.setFamily("Inter")
inter15bold.setPixelSize(15)
inter15bold.setBold(True)

inter16bold = QFont()
inter16bold.setFamily("Inter")
inter16bold.setPixelSize(16)
inter16bold.setBold(True)

inter18bold = QFont()
inter18bold.setFamily("Inter")
inter18bold.setPixelSize(18)
inter18bold.setBold(True)

inter24bold = QFont()
inter24bold.setFamily("Inter")
inter24bold.setPixelSize(24)
inter24bold.setBold(True)

inter48 = QFont()
inter48.setFamily("Inter")
inter48.setPixelSize(48)
inter48.setBold(True)

# Image class for QR code
class Image(qrcode.image.base.BaseImage):
 
    # constructor
    def __init__(self, border, width, box_size):
 
        # assigning border
        self.border = border

        # assigning  width
        self.width = width
 
        # assigning box size
        self.box_size = box_size

 
        # creating size
        size = (width + border * 2) * box_size
 
        # image
        self._image = QImage(size, size, QImage.Format.Format_RGB16)
 
        # initial image as white
        self._image.fill(Qt.GlobalColor.white)
 
 
    # pixmap method
    def pixmap(self):
 
        # returns image
        return QPixmap.fromImage(self._image)
 
    # drawrect method for drawing rectangle
    def drawrect(self, row, col):
 
        # creating painter object
        painter = QPainter(self._image)
 
        # drawing rectangle
        painter.fillRect(
            (col + self.border) * self.box_size,
            (row + self.border) * self.box_size,
            self.box_size, self.box_size,
            QtCore.Qt.GlobalColor.black)
 
 
# Main Window class
class QRWindow(QMainWindow):
    switch = pyqtSignal(str,dict)
    # constructor
    def __init__(self):
        QMainWindow.__init__(self)

        # setting window title
        self.setFixedSize(1280, 720)
        self.setWindowTitle("QR Code")
        self.setContentsMargins(100,-100,100,100)
        # setting geometry
        #self.setGeometry(100, 100, 300, 300)
        self.setStyleSheet(f'background-color: {DARK_MODE_BG}')

        # Label untuk logo
        logo = QLabel(self)
        logoImg = QPixmap("client/img/Puser.png")
        logo.setPixmap(logoImg)
        logo.move(572, 20)
        #logo.setAlignment(Qt.AlignmentFlag.AlignCenter)

        # Label untuk teks di bawah logo
        silakanText = QLabel(self)
        silakanText.setText("Silakan scan untuk pembayaran")
        silakanText.setStyleSheet(f'color: {PRIMARY_WHITE}')
        silakanText.move(480, 90)
        silakanText.setFont(inter24)

        checkOutText = QPushButton(self)
        checkOutText.setText("Done")
        checkOutText.setFixedSize(90,40)
        checkOutText.move(575, 660)
        checkOutText.setStyleSheet(f"color: {PRIMARY_BLACK}; background-color: {PRIMARY_GREEN}; border-color: {PRIMARY_BLACK}; border-radius: 12px")
        checkOutText.setFont(inter24bold)

        # from dita_window import ditaWindow
        checkOutText.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        checkOutText.clicked.connect(self.dita)
        # self.close()
        # self.checkOutText = ditaWindow()

        # silakanText.setAlignment(Qt.AlignmentFlag.AlignTop)
        # silakanText.setAlignment(Qt.AlignmentFlag.AlignCenter)
        # creating a label to show the qr code
        qRCode = QLabel(self)
        
        # get the text
        # with open('tes.txt') as f:
        #     text = f.read()
        text= []
        counter = 1
        
        print("\n======== GET PESANAN BY ID (HASIL) ========")
        response = requests.get("http://localhost:5000/api/detail-pesanan/"+str(counter))
        textdetail = response.json()
        # textdetail = json.dumps(text, indent=4) 
        text.append(textdetail)  
        print (textdetail)
        print(response)
        print(text)
        
        print("\n======== GET PESANAN BY ID (HASIL) ========")
        response = requests.get("http://localhost:5000/api/pesanan/"+str(counter))
        textkeranjang = response.json()
        # textkeranjang = json.dumps(text, indent=4)
        text.extend(textkeranjang)
        print(text)

        # creating a pix map of qr code
        qr_image = qrcode.make(text, image_factory = Image).pixmap()
        qr_image2 = qr_image.scaled(300,300)

        # set image to the label
        qRCode.setPixmap(qr_image2)
        qRCode.move(572,300)
        # qRCode.move(180,180)
        # qRCode.setAlignment(Qt.AlignmentFlag.AlignCenter)

        # creating a vertical layout
        layout = QGridLayout(self)
        # layout.columnCount() = 16
        # layout.rowCount() = 16

        # adding label to the layout
        layout.addWidget(logo, 0,1, alignment=Qt.AlignmentFlag.AlignCenter)
        # layout.addWidget(QPushButton('Log In'),0,0, alignment=Qt.AlignmentFlag.AlignLeft)
        # layout.addWidget(QLabel(''),1,3, alignment=Qt.AlignmentFlag.AlignRight)
        layout.addWidget(silakanText,1,1, alignment=Qt.AlignmentFlag.AlignCenter)
        layout.addWidget(qRCode,2,1,alignment=Qt.AlignmentFlag.AlignCenter)
        layout.addWidget(checkOutText,3,1,alignment=Qt.AlignmentFlag.AlignCenter)
        # creating a QWidget object
        widget = QWidget()

        # setting layout to the widget
        widget.setLayout(layout)

        # setting widget as central widget to the main window
        self.setCentralWidget(widget)


    # # method called by the line edit
    # def handleTextEntered(self):

    #     # get the text
    #     text = "Aku juga"

    #     # creating a pix map of qr code
    #     qr_image = qrcode.make(text, image_factory = Image).pixmap()

    #     # set image to the label
    #     self.label.setPixmap(qr_image)

    def dita(self):
        # self.ditadialog.show()
        self.switch.emit("dita",{})

if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = QRWindow()
    window.show()
    sys.exit(app.exec())